### ISSUE TITLE
Duplabetűk begépelése

### ISSUE THREAD

**Issue by mdanka** [mdanka/szozat#11]
fejlesztési lehetőség (hogy billentyűzettel is játszhatóbb legyen): ha már begépeltem egy S-et, és utána begépelek egy Z-t, akkor a Z ne egy új négyzetben jelenjen meg, hanem az S változzon át SZ betűvé.

**Comment by najibghadri** [comment]
Biztos hogy jó ötlet a dupla és tripla betűket egy betűként kezelni amúgy? Persze, abc szerint ezek betűk, de lehet hogy összezavaró lehet ha ezekre is külön kell gondolni.

**Comment by mdanka** [comment]
Igen, ez szándékos itt, mert a Scrabble-ben is így van.

De szerencsére van egy "szó reggelt" nevű változat is, abban külön vannak a
dupla betűk, próbáld ki nyugodtan azt is, az is tök jó!
