### ISSUE TITLE
Issue in validation of c/cs

### ISSUE THREAD

**Issue by verebd** [mdanka/szozat#40]
<img width="1318" alt="szozat-issue" src="https://user-images.githubusercontent.com/13396417/152640167-e6bfcf9b-0a30-4f90-8fdb-12800f1f481c.png">

The solution is "cirok" but it validates the letter "cs" as well.

**Comment by nemethricsi** [comment]
I guess it's solved based on https://github.com/mdanka/szozat/pull/36
