### ISSUE TITLE
A szólista nagyon hibás

### ISSUE THREAD

**Issue by deakjahn** [mdanka/szozat#42]
Bocs, de ez a szólista telistele van hibás szavakkal. Csak egy pár hirtelen:

yards
years
yours
weeks
works
xilem
zaina
zaman
zambó
zanót
zarán
zejna
zella
zelli
ziara
ziliz
zille
zimra
sphex
spuma
solen
samoa
sanel
sarel
salda
salpa
being
bejke
bekel
berna
doris
dotti
eliot
eliza
elián
eliél
elymus
fémip
galax
gotár
kalla
kalli
kairo
kamil
kelda
kerim
vikta
vilja
szirka
jukka

Értelmetlen is van benne elég sok, és nem magyar is. Igen, párra rá lehet fogni, hogy név, de nagyon nem kellene azokat sem.

**Comment by deakjahn** [comment]
Első gyors ellenőrzésképpen betettem a szólistát LibreOffice Writerbe, csak hogy lássam a hibákat első körben. Az elvileg jó magyar szavak között is rendkívül sok elgépelés van, ékezethiba, egyebek. Szerintem nagyon meg kellene fontolni valami más szólista használatát, talán egyszerűbb, mint ezt kijavítani. Megint pár példa:

vízgyógyitézet
végződöt
válvonás
válltóláz
vákum
válallat
vonorúd
utitáska
szügségtelen
szüületés
szervíz
szerencsejátéko
részlegeselsötétí
padlóviaszolóer
muzeum
meghatározhatatla
lefegőszerű
kompt
kerüketi
kaonizál
hányolódik
háromárbocos
hangarhívum
füldvezeték
eávgépíró
csőrlőgerendely
bürolkrácia
bűbályos

**Comment by mdanka** [comment]
Kösz a jelzéseket!

Ezek csak a szabályos tippek között vannak, nem a feladványok között, illetve jó része nem is ötbetűs, úgyhogy ezek annyira nem tűnnek kritikusnak.

FYI @rvv23

**Comment by mdanka** [comment]
De nyitva hagyom ezt az issue-t, hogy kiszűrjük majd ezeket a szavakat. Köszi!
